export const UPDATE_UISTATE = "UPDATE_UISTATE"
export const UPDATE_SIDE_BAR_VISIBLE = "UPDATE_SIDE_BAR_VISIBLE"
export const UPDATE_LOGIN_MODAL_VISIBLE = "UPDATE_LOGIN_MODAL_VISIBLE"
export const UPDATE_ALERT = "UPDATE_ALERT"
